#!/bin/bash

zenity --warning --text "Inserisci il probe a 3 dimensioni"

halcmd unlinkp arduino.probe_3d
halcmd unlinkp pyvcp.probe_3d_led

halcmd setp pyvcp.probe_3d_led True
halcmd setp arduino.probe_3d   True

exit 0
